Add ability to get token for hosted web sessions
smileidentity/smile-identity-core-ruby pull request #18
Opened 2021-10-08 08:55 UTC by sadick254

- Update README
- Add ability to get a token for hosted web sessions

2021-10-12 15:21 UTC, tamssokari approved these changes
this looks good. thank you for your service.

2021-10-12 18:11 UTC, beaglebets requested changes
One change needed, but overall looks great. I particularly appreciate your validations and test coverage.

2021-10-12 18:11 UTC, beaglebets commented on lib/smile-identity-core/web_api.rb
> +      request_params.merge!({ partner_id: @partner_id }).merge!(request_security)
The token endpoint does not accept `sec_key`. It only accepts `signature`. Because `request_security` defaults to the `sec_key`, so as not to be a breaking change when we introduced `signature` this would receive a an error response every time. We should also note in the readme that this function is only compatible with the v2 api key. Otherwise this looks fine.

2021-10-13 10:07 UTC, sadick254 commented on lib/smile-identity-core/web_api.rb
> +      request_params.merge!({ partner_id: @partner_id }).merge!(request_security)
In the definition `request_security` has a default param `use_new_signature` which has a default value of `true`. Calling `request_security` with no argument gives us a `signature` and not a `sec_key` as stated.

I have added an additional spec to show this.

2021-10-13 14:21 UTC, beaglebets approved these changes

2021-10-13 14:55 UTC, merged